services:
  trainer:
    build: .
    volumes:
      - ./mlruns:/lab/mlruns
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
#    command: tail -f /dev/null
    command: python -m lab.experiments.train_agent

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5000
