defaults:
  - env: sma_trends
  - agent: mc_agent
  - train: default
  - _self_
  - override hydra/job_logging: custom

seed: 1

env:
  params:
    simulations_length: 356

train:
  params:
    learning_rate: 0.0001
    trajectories_per_episode: 5
    episodes: 5000
