defaults:
  - env: sma_trends
  - agent: mc_agent
  - train: default
  - tuning: optuna
  - _self_
  - override hydra/job_logging: custom

seed: 1

experiment:
  name: Sweep-1Year

train:
  run_name: Trial
  params:
    learning_rate: 0.0001
    discounting: 0.95
    episodes: 3000

env:
  register_id: SimpleTrends-v1 
  options:
    simulations_length: 356
    init_days: 120
    mu: 0.0005
    random_trends: true
    short_sma: 26
    long_sma: 66

tuning:
  n_trials: 30
  search_space:
    env.options.short_sma:
      type: int
      min: 5
      max: 29
    env.options.long_sma:
      type: int
      min: 30
      max: 120
