defaults:
  - env: sma_trends
  - agent: mc_agent
  - train: default
  - _self_
  - override hydra/job_logging: custom

seed: 1

train:
  run_name: MCAgent_SimpleTrends_Run-2
  params:
    learning_rate: 0.0001
    trajectories_per_episode: 10
    threads_per_episode: 10
    episodes: 5000

env:
  options:
    simulations_length: 1000
    mu: -0.0005
